-- 3.1 Customers per brand
-- Distinct customers who purchased each brand


-- 3.2 Total value per brand
-- Revenue generated by each brand


-- 3.3 Rating distribution per brand
-- Average product rating by brand


-- 3.4 Orders per product category


-- 3.5 Customers per product category


-- 3.6 Brands per product category
-- Number of distinct brands within each category


-- 3.7 Revenue per product category
