-- 3.1 Total value per brand
-- Total revenue generated by each brand

SELECT pr.brand, SUM( oi.item_total) AS total_value
FROM order_items AS oi 
JOIN products AS pr ON pr.product_id=oi.product_id
GROUP BY pr.brand 
ORDER BY total_value DESC 



-- 3.2 Total value per product category
-- Total revenue generated by each product category

SELECT pr.category, SUM( oi.item_total) AS total_value
FROM order_items AS oi 
JOIN products AS pr ON pr.product_id=oi.product_id
GROUP BY pr.category 
ORDER BY total_value DESC 


-- 3.3 Electronics: orders and value per brand
-- Number of orders and total value per brand within the Electronics category

SELECT p.brand, COUNT (DISTINCT oi.order_id) AS total_orders, SUM(oi.item_total) AS total_value
FROM order_items AS oi 
JOIN products AS p ON p.product_id=oi.product_id
WHERE p.category ='Electronics'
GROUP BY p.brand 
ORDER BY total_orders DESC, total_value DESC


-- 3.4 Orders per product category
-- Number of orders containing products from each category


SELECT pr.category, COUNT( DISTINCT oi.order_id) AS total_orders
FROM order_items AS oi 
JOIN products AS pr ON pr.product_id=oi.product_id
GROUP BY pr.category 
ORDER BY total_orders DESC 


-- 3.5 Cancelled orders per brand
-- Number of cancelled orders containing products from each brand

SELECT p.brand, COUNT(DISTINCT o.order_id) AS cancelled_orders
FROM orders o
JOIN order_items AS oi ON o.order_id = oi.order_id
JOIN products AS p ON oi.product_id = p.product_id
WHERE o.order_status = 'cancelled'
GROUP BY p.brand
ORDER BY cancelled_orders DESC


