-- 3.1 Total value per brand
-- Total revenue generated by each brand


-- 3.2 Total value per product category
-- Total revenue generated by each product category


-- 3.3 Orders per product category
-- Number of orders containing products from each category


-- 3.4 Rating distribution per brand
-- Average product rating grouped by brand
